sources/app/src/Entity/Pot.php
<?php

namespace App\Entity;

use App\Repository\PotRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PotRepository::class)
 */
class Pot
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $label;

    /**
     * @ORM\Column(type="float")
     */
    private $current_amount;

    /**
     * @ORM\Column(type="float")
     */
    private $total_amount;

    /**
     * @ORM\ManyToOne(targetEntity=Child::class, inversedBy="pots")
     */
    private $recipient;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getCurrentAmount(): ?float
    {
        return $this->current_amount;
    }

    public function setCurrentAmount(float $current_amount): self
    {
        $this->current_amount = $current_amount;

        return $this;
    }

    public function getTotalAmount(): ?float
    {
        return $this->total_amount;
    }

    public function setTotalAmount(float $total_amount): self
    {
        $this->total_amount = $total_amount;

        return $this;
    }

    public function getRecipient(): ?Child
    {
        return $this->recipient;
    }

    public function setRecipient(?Child $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }
}

sources/app/src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email')
            ->add('picture', FileType::class,[
                'required' => false,
                'mapped' => false,
                'data_class' => null,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

sources/app/src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\AdminAsk;
use App\Entity\Appointment;
use App\Entity\Article;
use App\Entity\Category;
use App\Entity\Document;
use App\Entity\User;
use App\Entity\Virement;
use App\Entity\Visitor;
use App\Entity\Weedz;
use App\Form\AppointmentType;
use App\Form\ChangePasswordType;
use App\Form\ChildType;
use App\Form\DocumentType;
use App\Form\UserType;
use App\Form\VirementType;
use App\Form\RegistrationType;
use App\Form\VisitorType;
use App\Repository\ChildRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use App\Entity\Child;
use Symfony\Component\Validator\Constraints\DateTime;
use Symfony\Component\Validator\Constraints\Date;

class UserController extends AbstractController
{
    private function serialize($data)
    {
        return $this->container->get('jms_serializer')
            ->serialize($data, 'json');
    }

    /**
     * @Route("/registration", name="security_registration")
     * @param Request $request
     * @param UserPasswordEncoderInterface $encoder
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     * @throws \Exception
     */
    public function registration(Request $request, UserPasswordEncoderInterface $encoder){

        $user = new User();
        $registrationForm = $this->createForm(RegistrationType::class, $user);

        $registrationForm->handleRequest($request);
        if($registrationForm->isSubmitted() && $registrationForm->isValid()){
            $password = $encoder->encodePassword($user, $user->getPassword());
            $user->setPassword($password);
            $user->setCreatedAt(new \DateTime('now'));
            $user->setRoles(['ROLE_USER']);
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            if($user->isAdmin){
                $adminAsk = new AdminAsk();
                $adminAsk->setUser($this->getDoctrine()->getRepository(User::class)->find($user->getId()));
                $adminAsk->setStatus("Pending");
                $em->persist($adminAsk);
                $em->flush();
                $this->addFlash('success', "Nos services étudient actuellement votre demande d'accès administrateur, regardez vos mails !");
            }

            return $this->redirectToRoute('security_login');
        }

        return $this->render('user/registration.html.twig', [
            'registrationForm' => $registrationForm->createView(),
        ]);
    }


    /**
     * @Route("/login", name="security_login")
     * @param Request $request
     * @param AuthenticationUtils $authenticationUtils
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */

    public function login(Request $request, AuthenticationUtils $authenticationUtils){

        $visitor = new Visitor();
        $appointment = new Appointment();
        $visitorForm = $this->createForm(VisitorType::class, $visitor);
        $appointmentForm = $this->createForm(AppointmentType::class, $appointment);

        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();

        if($request->get('username')){
            
        }

        return $this->render('user/login.html.twig',[
            'visitorForm' => $visitorForm->createView(),
            'appointmentForm' => $appointmentForm->createView(),
            'error' => $error,
            'lastUsername' => $lastUsername
        ]);
    }

    /**
     * @Route("/login_visitor", name="security_login_visitor")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */

    public function loginVisitor(Request $request){

        $visitor = new Visitor();
        if($request->getMethod() === "POST"){

            $params = $request->request->all();
            if(isset($params)) {
                $visitor->setFirstname($params['visitor']['firstname']);
                $visitor->setLastname($params['visitor']['lastname']);
                $visitor->setEmail($params['visitor']['email']);

                $em = $this->getDoctrine()->getManager();
                $em->persist($visitor);
                $em->flush();
                return $this->redirectToRoute('feed', [], 301);
            }
        }
        return $this->redirectToRoute('security_login', [], 301);
    }

    /**
     * @Route("/logout", name="security_logout")
     */
    public function logout(){

    }

    /**
     * @Route("/me", name="my_space")
     */
    public function mySpace(){
        $userId = $this->getUser()->getId();
        $children = $this->getDoctrine()->getRepository(Child::class)->findChildrenByUserId($userId);

        return $this->render('user/my_space.html.twig',[
            'children' => $children
        ]);
    }

    /**
     * @Route("/feed", name="feed")
     */
    public function feed(){
        $categoryNames = $this->getDoctrine()->getRepository(Category::class)->findAllCategory();

        return $this->render('user/feed.html.twig', [
            'categoryNames' => $categoryNames
        ]);
    }


    /**
     * @Route("/child/add", name="add_child")
     */
    public function addChild(Request $request){
        $currentUser = $this->getUser();
        $child = new Child();
        $document = new Document();
        $childForm = $this->createForm(ChildType::class, $child);
        $documentForm = $this->createForm(DocumentType::class, $document);
        $documentForm->handleRequest($request);
        if($documentForm->isSubmitted() && $documentForm->isValid()) {
            $document->setCniParent($this->upload('cni_parent', $documentForm));
            $document->setParentPictureFace($this->upload('parent_picture_face', $documentForm));
            $document->setCniChild($this->upload('cni_child', $documentForm));
            $document->setChildPictureFace($this->upload('child_picture_face', $documentForm));
            $em = $this->getDoctrine()->getManager();
            $em->persist($document);
            $childRequest = $request->get('child');
            $child->setName($childRequest['name']);
            $child->setUser($this->getUser());
            // create row for weedz in db
            $child->setDocument($document);
            $em->persist($child);
            $em->flush();
            $weedz = new Weedz();
            $weedz->setChildId($this->getDoctrine()->getRepository(Child::class)->find($child->getId()));
            $weedz->setTotalCount(0.00);
            $weedz->setLastCollect(new \DateTime('now'));
            $em->persist($weedz);
            $em->flush();

            $this->addFlash('success', 'Enfant Ajouté !');
            return $this->redirectToRoute('my_space');
        }

        return $this->render('user/add_child.html.twig',[
            'childForm' => $childForm->createView(),
            'documentForm' => $documentForm->createView()
        ]);
    }

    /**
     * @Route("/appointment/create", name="create_appointment")
     * @param Request $request
     * @param \Swift_Mailer $mailer
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @throws \Exception
     */
    public function createAppointment(Request $request, \Swift_Mailer $mailer)
    {

        $appointment = $request->get('appointment');
        $appointmentObj = new Appointment();
        $date = new DateTime();
        $appointmentObj->setEmail($appointment['email']);
        $appointmentObj->setFirstname($appointment['firstname']);
        $appointmentObj->setName($appointment['name']);
        $str = $appointment['date']['year']."/".$appointment['date']['month']."/".$appointment['date']['day'];
        $appointmentObj->setDate(new \DateTime($str));

        $em = $this->getDoctrine()->getManager();
        $em->persist($appointmentObj);
        $em->flush();

        $message = (new \Swift_Message('Prise de RDV avec votre conseiller'))
            ->setFrom('no.reply.bankidz@gmail.com')
            ->setTo($appointment['email'])
            ->setBody(
                $this->renderView(
                // templates/emails/registration.html.twig
                    'email/appointment.html.twig',
                    ['appointment' => $appointmentObj]
                ),
                'text/html'
            );

        if ($mailer->send($message)) {
            $this->addFlash('success', 'Le mail a bien été envoyé');
        }else{
            $this->addFlash('error', "Une erreur est survenue lors de l'envoie du mail");
        }
        return $this->redirectToRoute('feed');
    }

    /**
     * @Route("/admin/validateAsk", name="admin_ask_validate")
     * @param Request $request
     * @param \Swift_Mailer $mailer
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function validate(Request $request, \Swift_Mailer $mailer){
        $id_ask = $request->query->get('id_ask');
        $id_user = $request->query->get('id_user');
        $adminAsk = $this->getDoctrine()->getRepository(AdminAsk::class)->find($id_ask);
        $user = $this->getDoctrine()->getRepository(User::class)->find($id_user);
        $user->setRoles(['ROLE_ADMIN']);
        $em = $this->getDoctrine()->getManager();
        $em->remove($adminAsk);
        $em->persist($user);
        $em->flush();
        $message = (new \Swift_Message('Accès Administrateur'))
            ->setFrom('no.reply.bankidz@gmail.com')
            ->setTo($user->getEmail())
            ->setBody(
                $this->renderView(
                    'email/adminAskValid.html.twig',
                    ['user' => $user]
                ),

sources/app/templates/user/add_child.html.twig
{% extends 'base.html.twig' %}
{% block title %}Mon espace{% endblock %}
{% block body %}
    <h1 style="text-align: center;">Ajouter un enfant</h1>
    <div class="container" style="margin-top: 50px">

       {{ form_start(documentForm, {action: path('add_child')})  }}
       {{ form_row(childForm.name,{label: "Nom de l'enfant"}, {class: "form-control"}) }}
        {{ form_row(documentForm.cni_parent ,{label: "CNI Parent"}, {class: "form-control"}) }}
        {{ form_row(documentForm.parent_picture_face ,{label: "Photo Parent"}, {class: "form-control"}) }}
        {{ form_row(documentForm.cni_child ,{label: "CNI Enfant"}, {class: "form-control"}) }}
        {{ form_row(documentForm.child_picture_face ,{label: "Photo Enfant"}, {class: "form-control"}) }}

        <button class="btn btn-primary" type="submit">Ajouter</button>
       {{  form_end(documentForm) }}
    </div>
{% endblock %}

sources/app/templates/user/add_pot.html.twig
{% extends 'base.html.twig' %}
{% block title %}Ajouter une Cagnotte{% endblock %}
{% block head %} <script src="https://js.stripe.com/v3/"></script> {% endblock %}
{% block body %}
    <h4>Nouvelle Cagnotte</h4>
    <div class="container">
        {{ form_start(potForm) }}
        {{ form_row(potForm.label, {label: 'Nom'}) }}
        {{ form_row(potForm.totalAmount, {label: 'Montant Max'}) }}
        {{ form_end(potForm) }}
    </div>
{% endblock %}

{% block javascript %}
{% endblock javascript %}

sources/app/templates/user/add_virement.html.twig
{% extends 'base.html.twig' %}
{% block title %}Ajouter un virement{% endblock %}
{% block head %} <script src="https://js.stripe.com/v3/"></script> {% endblock %}
{% block body %}
    <h4>Nouveau Virement</h4>
    <div class="container">
<script>

        </script>
{#        <form id="payment-form" action=""+url class="form-control">#}
{#            <input id="card-name" type="text">#}
{#            <!-- placeholder for Elements -->#}
{#            <div id="card-element"></div>#}
{#            <div id="card-errors" role="alert"></div>#}
{#            <button id="card-button" data-secret="{{ secret }}">#}
{#                Submit Payment#}
{#            </button>#}
{#        </form>#}

        {{ form_start(virementForm, {attr:{id: "payment-form" }}) }}

        <div id="card-element">
        <input type="number" class="form-control">
        </div>
        {{ form_row(virementForm.amount, {label: 'Montant', name: 'amount'}) }}
        {{ form_row(virementForm.comment, {label: 'Commentaire'}) }}
        {{ form_row(virementForm.isRecurrent, {label: 'Ce virement est récurrent'}) }}

        {{ form_end(virementForm) }}

    </div>
{% endblock %}

{% block javascript %}
<script>
var stripe = Stripe('pk_test_51H02x2Fp0I3CFkgQrkCNglAeH32Vk9s420wQ3s7EkQouTcld2arL7UMN1rVdLNykwJwYwtdOa7gtBAMoKcjs74xo00qJjHTEWT');
var elements = stripe.elements();
console.log(elements);

var style = {
    base: {
        color: "#32325d",
    }
};

var card = elements.create("card", { style: style });
card.mount("#card-element");

cardElement.on('change', function(event) {
    var displayError = document.getElementById('card-errors');
    if (event.error) {
        displayError.textContent = event.error.message;
    } else {
        displayError.textContent = '';
    }
});

var form = document.getElementById('payment-form');

form.addEventListener('submit', function(ev) {
    ev.preventDefault();
    stripe.confirmCardPayment(clientSecret, {
        payment_method: {
            card: card,
            billing_details: {
                name: 'Jenny Rosen'
            }
        }
    }).then(function(result) {
        if (result.error) {
            // Show error to your customer (e.g., insufficient funds)
            console.log(result.error.message);
        } else {
            // The payment has been processed!
            if (result.paymentIntent.status === 'succeeded') {
                // Show a success message to your customer
                // There's a risk of the customer closing the window before callback
                // execution. Set up a webhook or plugin to listen for the
                // payment_intent.succeeded event that handles any business critical
                // post-payment actions.
            }
        }
    });
});
</script>
{% endblock javascript %}

sources/app/templates/user/article.html.twig
{% extends 'base.html.twig' %}
{% block title %}Mon espace{% endblock %}
{% block body %}
    <div class="container">
    <i id="previous" class="fa fa-arrow-left fa-2x" aria-hidden="true"></i>
    <div class='article' style='margin-bottom: 30px;' id="{{ article.id }}">
        <div class='card'>{{ article.title }}
            <img src='{{article.picture}}' class='card-img-top' alt=''>
            <div class='card-body'>
                <p class='card-text'>{{article.content}}</p>
                <div><i id='arrowup' class='fa fa-arrow-up' aria-hidden='true'></i><p>{{ article.upCount }}</p></div>
                <div><i id='arrowdown' class='fa fa-arrow-down' aria-hidden='true'></i><p>{{ article.downCount }}</p></div>

                {% if app.user %}
                    <form id='commentForm' method='post' data-article="{{ article.id }}">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-8">
                                    <input id="content" class="form-control" placeholder='Ecrire ...' type='text' name='content'/>
                                </div>
                                <div class="col-4">
                                    <input id='submit_comment' type='submit' class="btn btn-primary">
                                </div>
                            </div>
                        </div>
                    </form>
                {% endif %}
                <div id="comment"></div>
            </div>
        </div>
    </div>
    <script>

        //Premier affichage
        var url = '/article/'+ $("#commentForm").data('article') +'/comments';
        console.log(url);
        $.get(url, function (data) {
            for(let i= 0; i < data.length; i++){
                $("#comment").append("<li class='list-group-item'><p class='username' id='"+ data[i].id+"' {% if app.user %} data-user='{{ app.user.username }}' {% endif %}><img src='"+ data[i].author.picture +"' heigth='250' width='250'>"+ data[i].author.username +"</p> - "+data[i].content+ " - " + formatDate(data[i].posted_at) +
                    "</li>");

                if($("p.username").data('user') === $($('p.username')[i]).text()){
                    $($("p.username")[i]).parent().append("<button class='deleteComment btn btn-primary'>Supprimer</button>")
                }

            }
        });


        $(document).ready(function(){

            /** Validate form **/

            $("#commentForm").validate({
                rules: {
                    content:{
                        required: true,
                        maxlength: 255
                    },
                },
                messages: {
                    content: "Le commentaire ne peut pas être vide"
                },
                submitHandler: function(form, event){
                    console.log('submit');
                    console.log($(form));
                    event.preventDefault(); // avoid to execute the actual submit of the form.
                    // //var form = $(this);
                    var url = Routing.generate('comment_post',{
                        'article_id': $('#commentForm').data('article')
                    });

                    // ajoute un commentaire
                    $.ajax({
                        type: "POST",
                        url: url,
                        dataType: "json",
                        contentType: 'application/json; charset=utf-8',
                        processData: false,
                        data: JSON.stringify($(form).serialize()), // serializes the form's elements.
                    }).done(function(){
                        var url = '/article/'+ $("#commentForm").data('article') +'/comments';
                        console.log(url);
                        $("#comment").children().remove();
                        /** remove text in comment form */
                        $(form).find('input[name=content]').val("");
                        $.get(url, function (data){
                            for(let i= 0; i < data.length; i++){
                                $("#comment").append("<li><p class='username' id='"+ data[i].id+"' {% if app.user %} data-user='{{ app.user.username }}' {% endif %}><img src='"+ data[i].author.picture +"' heigth=25 width=25>"+ data[i].author.username +"</p> - "+data[i].content+ " - " + formatDate(data[i].posted_at) +
                                    "</li>");
                                console.log($('p.username').text());
                                if($("p.username").data('user') === $($('p.username')[i]).text()){
                                    $($("p.username")[i]).parent().append("<button class='deleteComment btn btn-primary'  >Supprimer</button>")
                                }
                            }
                        });
                    });
                },
            });


            /** verifie l'association article_user in db **/
            $.ajax({
                type: "POST",
                url: "/article/"+ $(".article").attr('id') +"/user",
                dataType: "json",
                contentType: 'application/json; charset=utf-8',
                success: function(data){
                    console.log(data)
                }
            });

        });

        $(document).ajaxComplete(function() {

            $(".deleteComment").click(function () {
                var id = $(this).parent().children('.username').attr('id');
                var deleteCommentUrl = Routing.generate('delete_comment', {
                    "article_id": $(".article").attr('id'),
                    'comment_id': id
                });
                $.ajax({
                    type: "POST",
                    url: deleteCommentUrl,
                    dataType: "json",
                    contentType: 'application/json; charset=utf-8',
                    success: function (data) {
                        console.log(data)
                        $("#comment").children().remove();
                        console.log(data)
                        for (let i = 0; i < data.length; i++) {
                            $("#comment").append("<li><p class='username' id='" + data[i].id + "' {% if app.user %} data-user='{{ app.user.username }}' {% endif %}>" + data[i].author.username + "</p> - " + data[i].content + " - " + formatDate(data[i].posted_at) +
                                "<div><i class=\"fa fa-arrow-up\" aria-hidden=\"true\"></i></div>" +
                                "<div><i class=\"fa fa-arrow-down\" aria-hidden=\"true\"></i></div>" +
                                "</li>");
                            if($("p.username").data('user') === $($('p.username')[i]).text()){
                                $($("p.username")[i]).parent().append("<button class='deleteComment'>Supprimer</button>")
                            }
                        }
                    }

                });
            });
        });

        $("#arrowup").click(function(){

            console.log('click ajax up');
            $.ajax({
                url: '/article/'+$(".article").attr('id')+'/arrowup',
                type: 'POST',
                success: function(data){
                    console.log(data);
                    $("#arrowup").parent().children('p').text(data.up_count);
                    $("#arrowdown").parent().children('p').text(data.down_count);
                }
            });
        });


        $("#arrowdown").click(function(){

            console.log('click ajax down');
            $.ajax({
                url: '/article/'+$(".article").attr('id')+'/arrowdown',
                type: 'POST',
                success: function(data){
                    console.log(data);
                    $("#arrowdown").parent().children('p').text(data.down_count);
                    $("#arrowup").parent().children('p').text(data.up_count);
                }
            });
        });

        $("#previous").click(function(){
            location.href = document.referrer;
        });

        function formatDate(datetime) {
            console.log('test');
            var unFormatedDate = datetime.split("T");
            var date =  unFormatedDate[0];
            var formattedDate = new Date(date).toLocaleDateString();
            var unformatedHeure = unFormatedDate[1];
            var formatedHeure = unformatedHeure.split('+')[0];
            console.log(formatedHeure);
            console.log(formattedDate);

            return formattedDate + " à " + formatedHeure;
        }

    </script>
{% endblock %}

sources/app/templates/user/article_create.html.twig
{% extends 'base.html.twig' %}
{% block title %}Mon espace{% endblock %}
{% block body %}
    <div class="container">
        {{ form_start(articleForm) }}
        <button type="submit">Save</button>
        {{ form_end(articleForm) }}
    </div>
{% endblock %}

sources/app/templates/user/cashin.html.twig
{% extends 'base.html.twig' %}
{% block title %}Nos partenaires{% endblock %}
{% block body %}
    <div class="container">
        <h1 style="text-align: center;">Nos partenaires</h1>
        <div class="container" style="margin-top: 30px;">
            <h3>Mc Donald <span class="badge badge-primary">3</span></h3>
            <div class="row" style="margin-top: 30px;">
                <div class="col-3">
                    <div class="card">
                        <img src="..." class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text"></p>
                        </div>
                    </div>
                </div>
                <div class="col-3 offset-1">
                    <div class="card">
                        <img src="..." class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        </div>
                    </div>
                </div>
                <div class="col-3 offset-1">
                    <div class="card">
                        <img src="..." class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        </div>
                    </div>
                </div>
            </div>
            <button class="btn btn-primary" style="float: right;">Voir plus</button>
        </div>

        <div class="container" style="margin-top: 30px;">
            <h3>Décathlon <span class="badge badge-primary">9</span></h3>
            <div class="row" style="margin-top: 30px;">
                <div class="col-3">
                    <div class="card">
                        <img src="..." class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text"></p>
                        </div>
                    </div>
                </div>
                <div class="col-3 offset-1">
                    <div class="card">
                        <img src="..." class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        </div>
                    </div>
                </div>
                <div class="col-3 offset-1">
                    <div class="card">
                        <img src="..." class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-top: 30px;">
                <div class="col-3">
                    <div class="card">
                        <img src="..." class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text"></p>
                        </div>
                    </div>
                </div>
                <div class="col-3 offset-1">
                    <div class="card">
                        <img src="..." class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        </div>
                    </div>
                </div>
                <div class="col-3 offset-1">
                    <div class="card">
                        <img src="..." class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        </div>
                    </div>
                </div>
            </div>
            <button class="btn btn-primary" style="float: right;">Voir plus</button>
        </div>
    </div>
    <script type="text/javascript">

    </script>
{% endblock body %}

sources/app/templates/user/user_edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}Mon compte | Mes infos{% endblock %}
{% block body %}
    <h4 style="text-align:center;">Information utilisateur</h4>
    <div class="container">
    {{ form_start(userForm, {'action': path('change_password', {'user_id': app.user.id })}) }}

    {{ form_label(userForm.email) }}
    {{ form_widget(userForm.email) }}

    {{ form_label(userForm.picture, "Photo de profil") }}
    {{ form_widget(userForm.picture) }}

    <label class="col-form-label col-sm-2">Mot de passe</label>
    <input type="password" name="password" class="form-control">
    <button type="submit" class="btn btn-primary form-control" style="margin-top: 20px;">Modifier</button>
    {{ form_end(userForm) }}


    <a href="{{ path("change_password", {'user_id': app.user.id}) }}">Modifier le mot de passe</a>


{% endblock body %}